version: "3.9"

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://localhost:4000/api
        - CLIENT_URL=http://localhost:3000
    ports:
      - "3000:80"
    volumes:
      - ./client/nginx:/etc/nginx/conf.d
    depends_on:
      - backend

  backend:
    build: ./backend
    ports:
      - "4000:3000"
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mydb
      - MICROSERVICE_URL=http://0.0.0.0:5001
      - JWT_SECRET=123456+#
      - JWT_EXPIRES_IN=1d
      - CLIENT_URL=http://localhost:3000

    depends_on:
      - db
      - microservice

  microservice:
    build: ./microservice
    ports:
      - "5001:5000"

  db:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  db_data:
